### ISSUE TITLE
Setting xAxis.min and xAxis.max breaks tooltips on first and last points

### ISSUE THREAD

**Issue by markbairlift** [highslide-software/highcharts.com#3812]
Example: http://jsfiddle.net/gaap3f4f/

After setting xAxis.min and xAxis.max values in an attempt to get rid of the blank space to the sides of the chart, the tooltips on the first and last data points no longer work.

**Comment by it-can** [comment]
I have the same problem, exists in the latest versions

**Comment by stephanevanraes** [comment]
This is fixed in the latest release.

**Comment by it-can** [comment]
@stephanevanraes Issue still exists here when using the latest github versions: http://jsfiddle.net/gaap3f4f/1/
