### ISSUE TITLE
Highcharts v4.1.8 Point.update color bug

### ISSUE THREAD

**Issue by natee** [highslide-software/highcharts.com#4549]
When update a point's color, it dose not show the changed color right now until the mouse move over the point.

http://jsfiddle.net/4dtp4z2f/1/

**Comment by pawelfus** [comment]
*Internal note:*
Fixed on bugfix branch: http://jsfiddle.net/4dtp4z2f/2/

**Comment by natee** [comment]
@pawelfus Excuse me, In version v4.1.9 ,this issue was still exist?

**Comment by pawelfus** [comment]
It's not merged into the master branch. Bug above is the same as #4267 - once that bug will be fixed in the master branch, it will be included in the next release.

**Comment by natee** [comment]
Scatter chart has this problem.
http://jsfiddle.net/4dtp4z2f/3/

Bubble chart don't have this problem.
http://jsfiddle.net/5s6x7ok9/

**Comment by pawelfus** [comment]
You are using specific commit version from our branch tree. Instead use officially released versions, for example current one (4.2.3): http://jsfiddle.net/s8h049rx/ - works properly.

**Comment by natee** [comment]
Great ! I am using v4.2.0 . Thanks!
