### ISSUE TITLE
"Cannot read property '0' of undefined" error when stacked column chart is resized

### ISSUE THREAD

**Issue by peter-scarab** [highslide-software/highcharts.com#4558]
For a stacked column chart which is periodically updated, when the browser window is resized horizontally and the chart tries to change its width accordingly, a "Cannot read property '0' of undefined" error happens frequently.

In addition, when this happens, the points newly added to the second series start to appear on the column left to the last column, instead of the last column.

Demo: http://jsfiddle.net/peter_scarab/LLExL/5171/
Browser: Chrome 44
Tried with both the current master and bugfix branches.

**Comment by pawelfus** [comment]
Workarounds: 

- disable animation: http://jsfiddle.net/LLExL/5173/ 
- rebuild stacks manually: http://jsfiddle.net/LLExL/5174/  (may cause artifacts?)

*Internal note:*
Similar issue to #4557 - in short: we use `series.index` and point's index (`i`) from `series.points` array to get stack and corresponding points. In fact, `series.points` array may be unsynchronized ([this line](https://github.com/highslide-software/highcharts.com/blob/96a52a08dfdcc5f8ac0597b8326e1e8028d3714c/js/parts/Series.js#L772)) - in #4557 for example we remove points which are inside the break so we needed to rebuild stacks. 
I tried to use x-value instead of `i`, but this breaks multiple stacked points with the same x-value. We can not use `point.index` because dataGrouping doesn't provide such information. Any insights and/or suggestions?

**Comment by highslide-software** [comment]
What about using the x value plus som indicator in case the of multiple stacked points? So if the x value for that series has been taken before, we add 1,2,3,4 etc? It's just a thought, I don't know if it works well...

**Comment by pawelfus** [comment]
Let me know what do you think. I will write a test for that case if this is fine.

**Comment by pawelfus** [comment]
Solution above is more generic - we can revert #4557 commit, unless you think this is a good idea to rebuild stacks after modifying points array. We don't need to do that, but it will release a bit of memory (since some of stacks will disappear when are created inside the break). However, we would need to rebuild stacks so it would require extra CPU (a bit, but still!) ;)

**Comment by highslide-software** [comment]
Yes, it's probably better to revert the #4557 commit to save CPU.

> Let me know what do you think. I will write a test for that case if this is fine.

It seems like a robust solution. Maybe there's room for micro optimization, like constructing the empty stackIndicator, and generating the key?

**Comment by pawelfus** [comment]
Done in [this commit](https://github.com/highslide-software/highcharts.com/commit/7c143307695711065e43f7efe7ae4afcb7b03cf2) and [this one](https://github.com/highslide-software/highcharts.com/commit/ff989a382709cb8aed6aac2149efa28d7d166585). I wasn't sure about generating the key so it's split in two commits, in case of reverting. Thanks!

**Comment by highslide-software** [comment]
Excellent, thanks! I pulled the fix and the optimizations and reverted the 4557 fix.

**Comment by shashivardhan** [comment]
I still see a similar problem when using highstock with stacked bar chart and scroll bar enabled, which has 100 categories.

When I am using the scroll, I don't see the stacked bar on the chart and when I scroll back to initial position I'm getting this error 
"Cannot read property '0' of undefined" error when stacked column chart is resized"

**Comment by pawelfus** [comment]
Hi @shashivardhan - it's a bug in categorized axis, setting `cropThreshold` resolves the issue: https://jsfiddle.net/5xn92uht/5/ I see you reported this separately: #7944
